description: "Forge CLI — Modular Forge System Scaffold & Generator"

subcommands:
  scaffold:
    help: "Scaffold all modules defined in the config file"
    arguments: []

  py_scaffold:
    help: "Generate Python DTOs and other template-based Python files"
    arguments: []

  build:
    help: "Build the entire Forge project from the root directory"
    arguments: []

  clean:
    help: "Clean all CLion build artifacts (cmake-build-*) from the project root"
    arguments: []
  test:
    help: "Run the ForgeTestRunner to execute all internal tests"
    arguments: []
  multi:
    help: "Run multiple Forge CLI commands in sequence"
    arguments:
      - name: commands
        positional: true
        nargs: '+'
        help: "List of commands to run sequentially"