# module_layouts.yaml
# Module layout definitions for scaffolding
layouts:
  lib: ["src", "include"]
  exe: ["src", "include"]
  tool: ["src", "include"]
  plugin: ["src", "include"]
  test-only: ["bdd"]