TEMPLATES:
  root:
    cmakelists:
      template: templates/root/CMakeLists.txt.mustache
      output: forge/CMakeLists.txt

  lib:
    cmakelists:
      template: templates/lib/CMakelists.txt.mustache
      output: "forge/{{module_path}}/CMakeLists.txt"
    entrypoint:
      template: templates/lib/entrypoint_lib.mustache
      output: "{{DIR_src}}/{{module_name_snake_case}}_lib.cpp"
    header:
      template: templates/lib/header_lib.mustache
      output: "{{DIR_include}}/{{module_name_snake_case}}.hpp"

  py:
    config:
      master_config_dto:
        template: templates/py/py_dto_class.mustache
        values: config/dto/master_config_dto.yaml

  forge-core:
    headers:
      forgeable_interface:
        template: templates/cpp/crtp.hpp.mustache
        values: forge/forge-core/config/forgeable_values.yaml
        output: forge/forge-core/include/cppforge/core/forge/forgeable.hpp

      forge_interface:
        template: templates/cpp/crtp.hpp.mustache
        values: forge/forge-core/config/forge_values.yaml
        output: forge/forge-core/include/cppforge/core/forge/forge.hpp

      forgeable_traits:
        template: templates/cpp/traits.hpp.mustache
        values: forge/forge-core/config/forgeable_traits.yaml
        output: forge/forge-core/include/cppforge/core/forge/forgeable_traits.hpp

      forgeable_ptr:
        template: templates/cpp/type_alias_smart_ptr.hpp.mustache
        values: forge/forge-core/config/forgeable_ptr.yaml
        output: forge/forge-core/include/cppforge/core/forge/cppforge_ptr.hpp

      stateful_forgeable:
        template: templates/cpp/crtp.hpp.mustache
        values: forge/forge-core/config/stateless_forgeable_values.yaml
        output: forge/forge-core/include/cppforge/core/forge/stateless_forgeable.hpp

      stateless_forgeable:
        template: templates/cpp/crtp.hpp.mustache
        values: forge/forge-core/config/stateful_forgeable_values.yaml
        output: forge/forge-core/include/cppforge/core/forge/stateful_forgeable.hpp

      forge_cache:
        template: templates/cpp/crtp.hpp.mustache
        values: forge/forge-core/config/forge_cache.yaml
        output: forge/forge-core/include/cppforge/core/forge/forge_cache.hpp

      forge_resolver:
        template: templates/cpp/crtp.hpp.mustache
        values: forge/forge-core/config/forge_resolver.yaml
        output: forge/forge-core/include/cppforge/core/forge/forge_resolver.hpp

      forge_registry:
        template: templates/cpp/crtp.hpp.mustache
        values: forge/forge-core/config/forge_registry.yaml
        output: forge/forge-core/include/cppforge/core/forge/forge_registry.hpp