TEMPLATES:
  root:
    cmakelists:
      template: templates/root/CMakeLists.txt.mustache
      output: forge/CMakeLists.txt

  lib:
    cmakelists:
      template: templates/lib/CMakelists.txt.mustache
      output: "forge/{{module_path}}/CMakeLists.txt"

    entrypoint:
      template: templates/lib/entrypoint_lib.mustache
      output: "{{DIR_src}}/{{module_name_snake_case}}_lib.cpp"

    header:
      template: templates/lib/header_lib.mustache
      output: "{{DIR_include}}/{{module_name_snake_case}}.hpp"

  py:
    config:
      master_config_dto:
        template: templates/py/py_dto_class.mustache
        values: config/dto/master_config_dto.yaml