HEADER_GUARD: CPPFORGE_CORE_FORGE_FORGEABLE_HPP
HEADER_FILENAME: forgeable.hpp
DESCRIPTION: Base CRTP-style Forgeable interface for stateless execution.
INCLUDES:
  - "<string>"

NAMESPACE: cppforge::core::forge

CLASS_NAME: Forgeable

TEMPLATE_PARAM: Derived

ALIASES:
  - NAME: ExecutionLabel
    TYPE: std::string
    hasNext: false

has_alias: true

METHODS:
  - NAME: execute
    RETURN_TYPE: void
    PARAMS: []
    SPECIFIER: noexcept
    hasNext: true

  - NAME: getLabel
    RETURN_TYPE: ExecutionLabel
    PARAMS: []
    SPECIFIER: const noexcept
    hasNext: false

has_method: true
has_second_template_param: false