HEADER_FILENAME: forge.hpp
HEADER_GUARD: CPPFORGE_CORE_FORGE_FORGE_HPP
DESCRIPTION: Defines the CRTP-style Forge<T, ForgeableType> base for stateless factories.
NAMESPACE: cppforge::core::forge
INCLUDES:
  - "\"cppforge_ptr.hpp\""
  - "\"forgeable_traits.hpp\""
has_alias: true
ALIAS_EXECUTION_LABEL_TYPE: ForgeId
ALIAS_DATA_TYPE: std::string
CLASS_NAME: Forge
has_method: true
has_second_template_param: true
SECOND_TEMPLATE_PARAM: ForgeableType
METHOD_EXECUTE: create
METHOD_EXECUTE_IMPL: createImpl
METHOD_EXECUTE_RETURN_TYPE: ForgeablePtr
METHOD_LABEL: GetForgeId
METHOD_LABEL_IMPL: GetForgeIdImpl