HEADER_GUARD: CPPFORGE_CORE_FORGE_FORGE_MANAGER_HPP
HEADER_FILENAME: forge_manager.hpp
DESCRIPTION: Manages Forge registration and resolution.
NAMESPACE: cppforge::core::forge

INCLUDES:
  - "\"forge.hpp\""
  - "\"forge_resolver.hpp\""
  - "\"forge_registry.hpp\""
  - "\"forge_cache.hpp\""

CLASS_NAME: ForgeManager

TEMPLATE_PARAM: ForgeType

ALIASES:
  - NAME: ForgeId
    TYPE: std::string
    hasNext: true
  - NAME: CacheType
    TYPE: ForgeCache<ForgeType>
    hasNext: false

has_alias: true

CONSTRUCTOR:
  ENABLED: true
  PARAMS:
    - TYPE: CacheType*
      NAME: cache
  BODY: |
    cache_(cache)

METHODS:
  - NAME: resolve
    RETURN_TYPE: ForgeType*
    PARAMS:
      - DESCRIPTION: "const ForgeId& id"
        hasNext: false
    SPECIFIER: const noexcept
    hasNext: true

  - NAME: registerForge
    RETURN_TYPE: void
    PARAMS:
      - DESCRIPTION: "const ForgeId& id"
        hasNext: true
      - DESCRIPTION: "ForgeType* forge"
        hasNext: false
    SPECIFIER: noexcept
    hasNext: false

has_method: true
has_second_template_param: false

has_internal_storage: true
INTERNAL_STORAGE:
  - "CacheType* cache_;"

TRAITS:
  - NAME: cppforge::core::forge::ForgeResolver<ForgeType>
    isFirst: true
    hasNext: true
  - NAME: cppforge::core::forge::ForgeRegistry<ForgeType>
    isFirst: false
    hasNext: false