HEADER_GUARD: CPPFORGE_CORE_FORGE_CPPFORGE_PTR_HPP
HEADER_FILENAME: cppforge_ptr.hpp
NAMESPACE: cppforge::core::forge
includes:
  - "<memory>"
  - "\"forgeable_traits.hpp\""
BASE_TYPE: Forgeable
ALIAS_NAME: ForgeablePtr
TRAIT_NAME: is_forgeable