HEADER_GUARD: CPPFORGE_CORE_FORGE_FORGE_HPP
HEADER_FILENAME: forge.hpp
DESCRIPTION: Defines the CRTP-style Forge<T, ForgeableType> base for stateless factories.
NAMESPACE: cppforge::core::forge

INCLUDES:
  - "\"cppforge_ptr.hpp\""
  - "\"forgeable_traits.hpp\""

CLASS_NAME: Forge

TEMPLATE_PARAM: Derived
SECOND_TEMPLATE_PARAM: ForgeableType

ALIASES:
  - NAME: ForgeId
    TYPE: std::string
    hasNext: false

has_alias: true

METHODS:
  - NAME: create
    RETURN_TYPE: ForgeablePtr<ForgeableType>
    PARAMS: []
    SPECIFIER: noexcept
    hasNext: true

  - NAME: getForgeId
    RETURN_TYPE: ForgeId
    PARAMS: []
    SPECIFIER: const noexcept
    hasNext: false

has_method: true
has_second_template_param: true